In [8]:
#question 1

l=[i for i in range(2000,3201) if (i % 7==0) and (i % 5!=0)]        
print(l,sep='')  

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [9]:
#Question 2

k=int(input())
s=1
for i in range (k):
    s=s+s*i
print(str(k)+"!"+"=",s) 

5
5!= 120


In [13]:
#question3

d={}
n=int(input())
for i in range(1,n+1):
    d[i]=i*i
d

8


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [33]:
#Question 4
ch=input()
n=int(input())
if n<=len(ch):
    sh=ch[:n]+ch[n+1:]
    print(sh)



nada
0
ada


In [44]:
#question5
import numpy as np
N=np.array([[0,1],[2,3],[4,5]]) 
print(N)
l=[]
l=N.tolist()
print(l)

    


[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


In [45]:
#Question 6

import numpy as np
array1=np.array([0,1,2])
array2=np.array([2,1,0])
print(array1)
print(array2)
print(np.cov(array1,array2))

[0 1 2]
[2 1 0]
[[ 1. -1.]
 [-1.  1.]]


In [57]:
#Question7:

D=[]
R=[]
n=int(input())
for i in range (n):
    T=int(input())
    D.append(T)
print(D)    
for j in D:
    ch=(2 * 50* j)/30
    x=round(ch)
    R.append(x)
print(R)   

3
100
150
180
[100, 150, 180]
[333, 500, 600]
